# Generated by Django 2.1.5 on 2020-05-10 03:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tdidf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tdidf', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_manage.File')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word_name', models.CharField(max_length=128)),
                ('files', models.ManyToManyField(through='doc_manage.Tdidf', to='doc_manage.File')),
            ],
        ),
        migrations.AddField(
            model_name='tdidf',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_manage.Word'),
        ),
    ]
