# Generated by Django 2.2.10 on 2020-06-13 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='files',
        ),
        migrations.AddField(
            model_name='file',
            name='words_list',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Tdidf',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
