# Generated by Django 2.2.10 on 2020-06-13 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manage', '0003_file_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='created_of_article',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
