# Generated by Django 2.2.10 on 2020-06-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manage', '0006_auto_20200613_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
